name: Build and Release

on:
  push:
    branches: [ build ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: write
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [macOS-latest]
        include:
#          - os: ubuntu-latest
#            build-command: ./configure && make -j$(nproc)
#          - os: windows-latest
#            build-command: ./configure --toolchain=msvc --target-os=win64 --arch=x86_64 && make -j$(nproc)
          - os: macOS-latest
            build-command: ./configure --prefix=/usr/local --enable-gpl --enable-libass --enable-cuda-llvm --enable-nvenc --enable-libfreetype --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libopus && make -j$(sysctl -n hw.physicalcpu)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then 
            sudo apt-get install -y nasm yasm pkg-config libtool m4 autoconf automake cmake
          elif [ "${{ matrix.os }}" = "macOS-latest" ]; then 
            brew install automake fdk-aac git lame libass libtool libvorbis libvpx \
            opus sdl shtool texi2html theora wget x264 x265 xvid nasm
          fi

      - name: Build FFmpeg
        run: ${{ matrix.build-command }}
        shell: bash

      - name: Archive production artifacts
        run: |
          tar -czf ffmpeg.tar.gz ffmpeg ffprobe
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-${{ matrix.os }}
          path: ffmpeg.tar.gz
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: |
#            ffmpeg.tar.gz
